server {
    listen 80;
    server_name api.devbyanirban.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name api.devbyanirban.com;

    ssl_certificate /etc/letsencrypt/live/api.devbyanirban.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.devbyanirban.com/privkey.pem;

    root /var/www/public;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass app:9000;
        fastcgi_index index.php;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location ~ /\.ht {
        deny all;
    }
}